ALTER TABLE IN_TKAPR
ADD FOREIGN KEY (KAPR_DSKA)
REFERENCES IN_TDSKA(DSKA_DSKA)
;

ALTER TABLE IN_TKAPR
ADD FOREIGN KEY (KAPR_MVIN)
REFERENCES IN_TMVIN(MVIN_MVIN)
;

ALTER TABLE IN_TKAPR
ADD FOREIGN KEY (KAPR_TIUS)
REFERENCES US_TTIUS(TIUS_TIUS)
;

ALTER TABLE IN_TKAPR
ADD FOREIGN KEY (KAPR_PROV)
REFERENCES IN_TPROV(PROV_PROV)
;

