ALTER TABLE IN_TPRPR
ADD FOREIGN KEY (prpr_dska)
REFERENCES IN_TDSHA(DSHA_DSHA)
;

ALTER TABLE IN_TPRPR
ADD FOREIGN KEY (prpr_tius_crea)
REFERENCES US_TTIUS(TIUS_TIUS)
;

ALTER TABLE IN_TPRPR
ADD FOREIGN KEY (prpr_tius_update)
REFERENCES US_TTIUS(TIUS_TIUS)
;