ALTER TABLE US_TTIUS
ADD FOREIGN KEY (TIUS_PERS)
REFERENCES US_TPERS(PERS_PERS)
ON DELETE CASCADE ON UPDATE CASCADE
;

ALTER TABLE US_TTIUS
ADD FOREIGN KEY (TIUS_PERF)
REFERENCES US_TPERF(PERF_PERF)
ON DELETE CASCADE ON UPDATE CASCADE
;

ALTER TABLE US_TTIUS
ADD FOREIGN KEY (TIUS_SEDE)
REFERENCES EM_TSEDE(SEDE_SEDE)
;