ALTER TABLE IN_TRVHA
ADD FOREIGN KEY (RVHA_DSHA)
REFERENCES IN_TDSHA(DSHA_DSHA)
ON DELETE CASCADE ON UPDATE CASCADE
;

ALTER TABLE IN_TRVHA
ADD FOREIGN KEY (RVHA_CLIEN)
REFERENCES US_TCLIEN(CLIEN_CLIEN)
ON DELETE CASCADE ON UPDATE CASCADE
;

ALTER TABLE IN_TRVHA
ADD FOREIGN KEY (RVHA_TIUS)
REFERENCES US_TTIUS(TIUS_TIUS)
ON UPDATE CASCADE
;