--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(1, 11,UPPER('A'), 'CAJA', 1105, 'Registra la existencia en dinero efectivo o en cheques con que cuenta el ente económico, tanto en moneda nacional como extranjera, disponible en forma inmediata.');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(2, 11,UPPER('A'), 'BANCOS', 1110, 'Registra el valor de los depósitos constituidos por el ente económico en moneda nacional y extranjera,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(3, 12,UPPER('A'), 'ACCIONES', 1205, 'Registra el costo histórico de las inversiones realizadas por el ente económico en sociedades por acciones y/o asimiladas,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(4, 12,UPPER('A'), 'CUOTAS O PARTES DE INTRÉS SOCIAL', 1210, 'Registra el costo histórico de las inversiones realizadas por el ente económico en sociedades de responsabilidad limitada y/o asimiladas,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(5, 13,UPPER('A'), 'CLIENTES', 1305, 'Registra los valores a favor del ente económico y a cargo de clientes nacionales y/o extranjeros de cualquier naturaleza,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(6, 13,UPPER('A'), 'CUENTAS CORRIENTES COMERCIALES', 1310, 'Registra el valor de las operaciones comerciales celebradas entre dos entes económicos, reguladas por las normas legales vigentes,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(7, 14,UPPER('A'), 'MATERIA PRIMA', 1405, 'Registra el valor de los elementos básicos adquiridos a nivel nacional o internacional, para uso en el proceso de fabricación o producción,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(8, 14,UPPER('A'), 'PRODUCTOS EN PROCESO', 1410, 'Registra el costo de los artículos semielaborados, es decir que poseen un cierto grado de terminación,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(9, 21,UPPER('A'), 'BANCOS NACIONALES', 2105, 'Registra el monto del capital de las obligaciones contraídas por el ente económico, en moneda nacional o extranjera,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(10, 21,UPPER('A'), 'BANCOS DEL EXTERIOR', 2110, 'Registra el monto del capital de las obligaciones contraídas por el ente económico, en moneda extranjera,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(11, 22,UPPER('A'), 'NACIONALES', 2205, 'Registra las obligaciones contraídas, en moneda nacional o extranjera por el ente económico con proveedores para la adquisición de bienes,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(12, 22,UPPER('A'), 'DEL EXTERIOR', 2210, 'Registra el valor de las obligaciones a cargo del ente económico y a favor de extranjeros por concepto de la adquisición de bienes,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(13, 23,UPPER('A'), 'CUENTAS CORRIENTES COMERCIALES', 2305, 'Registra el valor adeudado por el ente económico a favor de terceros por conceptos diferentes a los proveedores y obligaciones financieras,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(14, 23,UPPER('A'), 'A CASA MATRIZ', 2310, 'Registra las deudas a cargo del ente económico y a favor de la casa matriz o principal por conceptos diferentes a los definidos,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(15, 24,UPPER('A'), 'DE RENTAS Y COMPLEMENTARIOS', 2404, 'Registra el valor pendiente de pago por concepto de impuesto de renta y complementarios del respectivo ejercicio,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(16, 24,UPPER('A'), 'IMPUESTOS SOBRE LAS VENTAS QUE PAGAR', 2408, 'Registra tanto el valor recaudado o causado como el valor pagado o causado, en la adquisición o venta de bienes producidos,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(17, 31,UPPER('A'), 'CAPITAL SUSCRITO Y PAGADO', 3105, 'Registra el ingreso real al patrimonio del ente económico, de los aportes efectuados por los accionistas,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(18, 31,UPPER('A'), 'APORTES SOCIALES', 3115, 'Registra el valor de los aportes realizados por los socios al momento de constituir el ente económico respaldados,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(19, 32,UPPER('A'), 'DONACIONES', 3210, 'Registra los valores acumulados que el ente económico ha recibido por concepto de donaciones de bienes y valores,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(20, 32,UPPER('A'), 'CRÉDITO MERCANTIL', 3215, 'Registra la contrapartida o cuenta de valuación del crédito mercantil formado o estimado contabilizado en la subcuenta 160505.');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(21, 33,UPPER('A'), 'RESERVAS OBLIGATORIAS', 3305, 'Registra los valores apropiados de las utilidades líquidas, conforme a mandatos legales, con el propósito de proteger el patrimonio social,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(22, 33,UPPER('A'), 'RESERVAS ESTATUTARIAS', 3310, 'Registra los valores de todas aquellas partidas apropiadas de acuerdo con lo contemplado en los estatutos sociales,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(23, 34,UPPER('A'), 'AJUSTES POR INFLACIÓN', 3405, 'Registra el ajuste por inflación del patrimonio del ente económico, así como de los activos en período improductivo,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(24, 34,UPPER('A'), 'SANEAMIENTO FISCAL', 3410, 'Registra el saldo que por virtud de normas legales especiales generaron ajustes a la contabilidad del ente económico,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(25, 41,UPPER('A'), 'AGRICOLA, GANADERA, CAZA Y SILVICULTURA', 4105, 'Registra el valor de los ingresos obtenidos por el ente económico en la cría, levante y ceba de semovientes,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(26, 41,UPPER('A'), 'PESCA', 4110, 'Registra el valor de los ingresos obtenidos por el ente económico en la venta de productos y prestación de servicios,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(27, 42,UPPER('A'), 'OTRAS VENTAS', 4205, 'Registra el valor de los ingresos obtenidos por el ente económico en la venta ocasional de ciertos bienes que no corresponden propiamente al desarrollo,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(28, 42,UPPER('A'), 'FINANCIEROS', 4210, 'Registra el valor de los ingresos obtenidos por el ente económico por concepto de rendimientos de capital a través de actividades,');
--INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(29, 47,UPPER('A'), 'CORRECIÓN MONETARIA', 4705, 'Registra las partidas crédito y débito correspondientes a los ajustes por inflación, efectuados a los valores contabilizados,');

--INSERT JOHN 

INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(1,11,UPPER('A'),'CAJA',1105,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(2,11,UPPER('A'),'BANCOS',1110,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(3,11,UPPER('A'),'REMESAS EN TRANSITO',1115,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(4,11,UPPER('A'),'CUENTAS DE AHORRO',1120,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(5,11,UPPER('A'),'FONDOS',1125,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(6,12,UPPER('A'),'ACCIONES',1205,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(7,12,UPPER('A'),'CUOTAS O PARTES DE INTERES SOCIAL',1210,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(8,12,UPPER('A'),'BONOS',1215,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(9,12,UPPER('A'),'CEDULAS',1220,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(10,12,UPPER('A'),'CERTIFICADOS',1225,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(11,12,UPPER('A'),'PAPELES COMERCIALES',1230,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(12,12,UPPER('A'),'TITULOS',1235,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(13,12,UPPER('A'),'ACEPTACIONES BANCARIAS O FINANCIERAS',1240,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(14,12,UPPER('A'),'DERECHOS FIDUCIARIOS',1245,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(15,12,UPPER('A'),'DERECHOS DE RECOMPRA DE INVERSIONES NEGOCIADAS (REPOS)',1250,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(16,12,UPPER('A'),'OBLIGATORIAS',1255,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(17,12,UPPER('A'),'CUENTAS EN PARTICIPACION',1260,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(18,12,UPPER('A'),'OTRAS INVERSIONES',1295,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(19,12,UPPER('A'),'PROVISIONES',1299,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(20,13,UPPER('A'),'CLIENTES',1305,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(21,13,UPPER('A'),'CUENTAS CORRIENTES COMERCIALES',1310,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(22,13,UPPER('A'),'CUENTAS POR COBRAR A CASA MATRIZ',1315,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(23,13,UPPER('A'),'CUENTAS POR COBRAR A VINCULADOS ECONOMICOS',1320,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(24,13,UPPER('A'),'CUENTAS POR COBRAR A SOCIOS Y ACCIONISTAS',1325,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(25,13,UPPER('A'),'APORTES POR COBRAR',1328,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(26,13,UPPER('A'),'ANTICIPOS Y AVANCES',1330,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(27,13,UPPER('A'),'CUENTAS DE OPERACION CONJUNTA',1332,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(28,13,UPPER('A'),'DEPOSITOS',1335,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(29,13,UPPER('A'),'PROMESAS DE COMPRA VENTA',1340,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(30,13,UPPER('A'),'INGRESOS POR COBRAR',1345,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(31,13,UPPER('A'),'RETENCION SOBRE CONTRATOS',1350,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(32,13,UPPER('A'),'ANTICIPO DE IMPUESTOS Y CONTRIBUCIONES O SALDOS A FAVOR',1355,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(33,13,UPPER('A'),'RECLAMACIONES',1360,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(34,13,UPPER('A'),'CUENTAS POR COBRAR A TRABAJADORES',1365,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(35,13,UPPER('A'),'PRESTAMOS A PARTICULARES',1370,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(36,13,UPPER('A'),'DEUDORES VARIOS',1380,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(37,13,UPPER('A'),'DERECHOS DE RECOMPRA DE CARTERA NEGOCIADA',1385,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(38,13,UPPER('A'),'DEUDAS DE DIFICIL COBRO',1390,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(39,13,UPPER('A'),'PROVISIONES',1399,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(40,14,UPPER('A'),'MATERIAS PRIMAS',1405,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(41,14,UPPER('A'),'PRODUCTOS EN PROCESO',1410,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(42,14,UPPER('A'),'OBRAS DE CONSTRUCCION EN CURSO',1415,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(43,14,UPPER('A'),'OBRAS DE URBANISMO',1417,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(44,14,UPPER('A'),'CONTRATOS EN EJECUCION',1420,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(45,14,UPPER('A'),'CULTIVOS EN DESARROLLO',1425,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(46,14,UPPER('A'),'PRODUCTOS TERMINADOS',1430,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(47,14,UPPER('A'),'MERCANCIAS NO FABRICADAS POR LA EMPRESA',1435,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(48,14,UPPER('A'),'BIENES RAICES PARA LA VENTA',1440,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(49,14,UPPER('A'),'SEMOVIENTES',1445,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(50,14,UPPER('A'),'TERRENOS',1450,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(51,14,UPPER('A'),'MATERIALES, REPUESTOS Y ACCESORIOS',1455,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(52,14,UPPER('A'),'ENVASES Y EMPAQUES',1460,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(53,14,UPPER('A'),'INVENTARIOS EN TRANSITO',1465,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(54,14,UPPER('A'),'PROVISIONES',1499,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(55,15,UPPER('A'),'TERRENOS',1504,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(56,15,UPPER('A'),'MATERIALES PROYECTOS PETROLEROS',1506,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(57,15,UPPER('A'),'CONSTRUCCIONES EN CURSO',1508,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(58,15,UPPER('A'),'MAQUINARIA Y EQUIPOS EN MONTAJE',1512,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(59,15,UPPER('A'),'CONSTRUCCIONES Y EDIFICACIONES',1516,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(60,15,UPPER('A'),'MAQUINARIA Y EQUIPO',1520,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(61,15,UPPER('A'),'EQUIPO DE OFICINA',1524,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(62,15,UPPER('A'),'EQUIPO DE COMPUTACION Y COMUNICACION',1528,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(63,15,UPPER('A'),'EQUIPO MEDICO - CIENTIFICO',1532,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(64,15,UPPER('A'),'EQUIPO DE HOTELES Y RESTAURANTES',1536,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(65,15,UPPER('A'),'FLOTA Y EQUIPO DE TRANSPORTE',1540,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(66,15,UPPER('A'),'FLOTA Y EQUIPO FLUVIAL Y/O MARITIMO',1544,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(67,15,UPPER('A'),'FLOTA Y EQUIPO AEREO',1548,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(68,15,UPPER('A'),'FLOTA Y EQUIPO FERREO',1552,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(69,15,UPPER('A'),'ACUEDUCTOS PLANTAS Y REDES',1556,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(70,15,UPPER('A'),'ARMAMENTO DE VIGILANCIA',1560,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(71,15,UPPER('A'),'ENVASES Y EMPAQUES',1562,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(72,15,UPPER('A'),'PLANTACIONES AGRICOLAS Y FORESTALES',1564,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(73,15,UPPER('A'),'VIAS DE COMUNICACION',1568,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(74,15,UPPER('A'),'MINAS Y CANTERAS',1572,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(75,15,UPPER('A'),'POZOS ARTESIANOS',1576,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(76,15,UPPER('A'),'YACIMIENTOS',1580,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(77,15,UPPER('A'),'SEMOVIENTES',1584,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(78,15,UPPER('A'),'PROPIEDADES PLANTA Y EQUIPO EN TRANSITO',1588,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(79,15,UPPER('A'),'DEPRECIACION ACUMULADA',1592,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(80,15,UPPER('A'),'DEPRECIACION DIFERIDA',1596,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(81,15,UPPER('A'),'AMORTIZACION ACUMULADA',1597,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(82,15,UPPER('A'),'AGOTAMIENTO ACUMULADO',1598,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(83,15,UPPER('A'),'PROVISIONES',1599,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(84,16,UPPER('A'),'CREDITO MERCANTIL',1605,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(85,16,UPPER('A'),'MARCAS',1610,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(86,16,UPPER('A'),'PATENTES',1615,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(87,16,UPPER('A'),'CONCESIONES Y FRANQUICIAS',1620,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(88,16,UPPER('A'),'DERECHOS',1625,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(89,16,UPPER('A'),'KNOW HOW',1630,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(90,16,UPPER('A'),'LICENCIAS',1635,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(91,16,UPPER('A'),'AMORTIZACION ACUMULADA',1698,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(92,16,UPPER('A'),'PROVISIONES',1699,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(93,17,UPPER('A'),'GASTOS PAGADOS POR ANTICIPADO',1705,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(94,17,UPPER('A'),'CARGOS DIFERIDOS',1710,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(95,17,UPPER('A'),'COSTOS DE EXPLORACION POR AMORTIZAR',1715,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(96,17,UPPER('A'),'COSTOS DE EXPLOTACION Y DESARROLLO',1720,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(97,17,UPPER('A'),'CARGOS POR CORRECCION MONETARIA DIFERIDA',1730,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(98,17,UPPER('A'),'AMORTIZACION ACUMULADA',1798,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(99,18,UPPER('A'),'BIENES DE ARTE Y CULTURA',1805,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(100,18,UPPER('A'),'DIVERSOS',1895,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(101,18,UPPER('A'),'PROVISIONES',1899,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(102,19,UPPER('A'),'DE INVERSIONES',1905,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(103,19,UPPER('A'),'DE PROPIEDADES PLANTA Y EQUIPO',1910,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(104,19,UPPER('A'),'DE OTROS ACTIVOS',1995,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(105,21,UPPER('A'),'BANCOS NACIONALES',2105,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(106,21,UPPER('A'),'BANCOS DEL EXTERIOR',2110,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(107,21,UPPER('A'),'CORPORACIONES FINANCIERAS',2115,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(108,21,UPPER('A'),'COMPAÑIAS DE FINANCIAMIENTO COMERCIAL',2120,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(109,21,UPPER('A'),'CORPORACIONES DE AHORRO Y VIVIENDA',2125,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(110,21,UPPER('A'),'ENTIDADES FINANCIERAS DEL EXTERIOR',2130,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(111,21,UPPER('A'),'COMPROMISOS DE RECOMPRA DE INVERSIONES NEGOCIADAS',2135,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(112,21,UPPER('A'),'COMPROMISOS DE RECOMPRA DE CARTERA NEGOCIADA',2140,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(113,21,UPPER('A'),'OBLIGACIONES GUBERNAMENTALES',2145,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(114,21,UPPER('A'),'OTRAS OBLIGACIONES',2195,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(115,22,UPPER('A'),'NACIONALES',2205,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(116,22,UPPER('A'),'DEL EXTERIOR',2210,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(117,22,UPPER('A'),'CUENTAS CORRIENTES COMERCIALES',2215,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(118,22,UPPER('A'),'CASA MATRIZ',2220,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(119,22,UPPER('A'),'COMPAÑIAS VINCULADAS',2225,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(120,23,UPPER('A'),'CUENTAS CORRIENTES COMERCIALES',2305,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(121,23,UPPER('A'),'A CASA MATRIZ',2310,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(122,23,UPPER('A'),'A COMPAÑIAS VINCULADAS',2315,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(123,23,UPPER('A'),'A CONTRATISTAS',2320,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(124,23,UPPER('A'),'ORDENES DE COMPRA POR UTILIZAR',2330,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(125,23,UPPER('A'),'COSTOS Y GASTOS POR  PAGAR',2335,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(126,23,UPPER('A'),'INSTALAMENTOS POR PAGAR',2340,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(127,23,UPPER('A'),'ACREEDORES OFICIALES',2345,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(128,23,UPPER('A'),'REGALIAS POR PAGAR',2350,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(129,23,UPPER('A'),'DEUDAS CON ACCIONISTAS O SOCIOS',2355,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(130,23,UPPER('A'),'DIVIDENDOS O PARTICIPACIONES POR PAGAR',2360,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(131,23,UPPER('A'),'RETENCION EN LA FUENTE',2365,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(132,23,UPPER('A'),'RETENCIONES Y APORTES DE NOMINA',2370,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(133,23,UPPER('A'),'CUOTAS POR DEVOLVER',2375,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(134,23,UPPER('A'),'ACREEDORES VARIOS',2380,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(135,24,UPPER('A'),'DE RENTA Y COMPLEMENTARIOS',2404,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(136,24,UPPER('A'),'IMPUESTO SOBRE LAS VENTAS POR PAGAR',2408,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(137,24,UPPER('A'),'DE INDUSTRIA Y COMERCIO',2412,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(138,24,UPPER('A'),'A LA PROPIEDAD RAIZ',2416,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(139,24,UPPER('A'),'DERECHOS SOBRE INSTRUMENTOS PUBLICOS',2420,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(140,24,UPPER('A'),'DE VALORIZACION',2424,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(141,24,UPPER('A'),'DE TURISMO',2428,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(142,24,UPPER('A'),'TASA POR UTILIZACION DE PUERTOS',2432,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(143,24,UPPER('A'),'DE VEHICULOS',2436,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(144,24,UPPER('A'),'DE ESPECTACULOS PUBLICOS',2440,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(145,24,UPPER('A'),'DE HIDROCARBUROS Y MINAS',2444,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(146,24,UPPER('A'),'REGALIAS E IMPUESTOS A LA PEQUEÑA Y MEDIANA MINERIA',2448,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(147,24,UPPER('A'),'A LAS EXPORTACIONES CAFETERAS',2452,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(148,24,UPPER('A'),'A LAS IMPORTACIONES',2456,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(149,24,UPPER('A'),'CUOTAS DE FOMENTO',2460,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(150,24,UPPER('A'),'DE LICORES, CERVEZAS Y CIGARRILLOS',2464,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(151,24,UPPER('A'),'AL SACRIFICIO DE GANADO',2468,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(152,24,UPPER('A'),'AL AZAR Y JUEGOS',2472,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(153,24,UPPER('A'),'OTROS',2495,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(154,25,UPPER('A'),'SALARIOS POR PAGAR',2505,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(155,25,UPPER('A'),'CESANTIAS CONSOLIDADAS',2510,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(156,25,UPPER('A'),'INTERESES SOBRE CESANTIAS',2515,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(157,25,UPPER('A'),'PRIMA DE SERVICIOS',2520,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(158,25,UPPER('A'),'VACACIONES CONSOLIDADAS',2525,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(159,25,UPPER('A'),'PRESTACIONES EXTRALEGALES',2530,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(160,25,UPPER('A'),'PENSIONES POR PAGAR',2532,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(161,25,UPPER('A'),'CUOTAS PARTES PENSIONES DE JUBILACION',2535,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(162,25,UPPER('A'),'INDEMNIZACIONES LABORALES',2540,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(163,26,UPPER('A'),'PARA COSTOS Y GASTOS',2605,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(164,26,UPPER('A'),'PARA OBLIGACIONES LABORALES',2610,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(165,26,UPPER('A'),'PARA OBLIGACIONES FISCALES',2615,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(166,26,UPPER('A'),'PENSIONES DE JUBILACION',2620,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(167,26,UPPER('A'),'PARA OBRAS DE URBANISMO',2625,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(168,26,UPPER('A'),'PARA MANTENIMIENTO Y REPARACIONES',2630,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(169,26,UPPER('A'),'PARA CONTINGENCIAS',2635,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(170,26,UPPER('A'),'PARA OBLIGACIONES DE GARANTIAS',2640,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(171,26,UPPER('A'),'PROVISIONES DIVERSAS',2695,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(172,27,UPPER('A'),'INGRESOS RECIBIDOS POR ANTICIPADO',2705,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(173,27,UPPER('A'),'ABONOS DIFERIDOS',2710,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(174,27,UPPER('A'),'UTILIDAD DIFERIDA EN VENTAS A PLAZOS',2715,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(175,27,UPPER('A'),'CREDITO POR CORRECCION MONETARIA DIFERIDA',2720,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(176,27,UPPER('A'),'IMPUESTOS DIFERIDOS',2725,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(177,28,UPPER('A'),'ANTICIPOS Y AVANCES RECIBIDOS',2805,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(178,28,UPPER('A'),'DEPOSITOS RECIBIDOS',2810,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(179,28,UPPER('A'),'INGRESOS RECIBIDOS PARA TERCEROS',2815,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(180,28,UPPER('A'),'CUENTAS DE OPERACION CONJUNTA',2820,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(181,28,UPPER('A'),'RETENCIONES A TERCEROS SOBRE CONTRATOS',2825,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(182,28,UPPER('A'),'EMBARGOS JUDICIALES',2830,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(183,28,UPPER('A'),'ACREEDORES DEL SISTEMA',2835,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(184,28,UPPER('A'),'CUENTAS EN PARTICIPACION',2840,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(185,28,UPPER('A'),'DIVERSOS',2895,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(186,29,UPPER('A'),'BONOS EN CIRCULACION',2905,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(187,29,UPPER('A'),'BONOS OBLIGATORIAMENTE CONVERTIBLES EN ACCIONES',2910,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(188,29,UPPER('A'),'PAPELES COMERCIALES',2915,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(189,31,UPPER('A'),'CAPITAL SUSCRITO Y PAGADO',3105,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(190,31,UPPER('A'),'ACCIONES, CUOTAS O PARTES DE INTERES SOCIAL PROPIAS READQUIRIDAS (DB)',3110,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(191,31,UPPER('A'),'APORTES SOCIALES',3115,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(192,31,UPPER('A'),'CAPITAL ASIGNADO',3120,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(193,31,UPPER('A'),'INVERSION SUPLEMENTARIA AL CAPITAL ASIGNADO',3125,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(194,31,UPPER('A'),'CAPITAL DE PERSONAS NATURALES',3130,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(195,31,UPPER('A'),'APORTES DEL ESTADO',3135,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(196,31,UPPER('A'),'FONDO SOCIAL',3140,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(197,32,UPPER('A'),'PRIMA EN COLOCACION DE ACCIONES, CUOTAS O PARTES DE INTERES',3205,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(198,32,UPPER('A'),'DONACIONES',3210,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(199,32,UPPER('A'),'CREDITO MERCANTIL',3215,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(200,33,UPPER('A'),'RESERVAS OBLIGATORIAS',3305,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(201,33,UPPER('A'),'RESERVAS ESTATUTARIAS',3310,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(202,33,UPPER('A'),'RESERVAS OCASIONALES',3315,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(203,34,UPPER('A'),'AJUSTES POR INFLACION',3405,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(204,34,UPPER('A'),'SANEAMIENTO FISCAL',3410,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(205,34,UPPER('A'),'AJUSTES POR INFLACION DECRETO 3019 DE 1989',3415,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(206,35,UPPER('A'),'DIVIDENDOS DECRETADOS EN ACCIONES',3505,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(207,35,UPPER('A'),'PARTICIPACIONES DECRETADAS EN CUOTAS O PARTES DE INTERES SOCIAL',3510,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(208,36,UPPER('A'),'UTILIDAD DEL EJERCICIO',3605,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(209,36,UPPER('A'),'PERDIDA DEL EJERCICIO',3610,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(210,37,UPPER('A'),'UTILIDADES O EXCEDENTES ACUMULADOS',3705,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(211,37,UPPER('A'),'PERDIDAS ACUMULADAS',3710,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(212,38,UPPER('A'),'DE INVERSIONES',3805,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(213,38,UPPER('A'),'DE PROPIEDADES PLANTA Y EQUIPO',3810,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(214,38,UPPER('A'),'DE OTROS ACTIVOS',3895,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(215,41,UPPER('A'),'AGRICULTURA, GANADERIA, CAZA Y SILVICULTURA',4105,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(216,41,UPPER('A'),'PESCA',4110,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(217,41,UPPER('A'),'EXPLOTACION DE MINAS Y CANTERAS',4115,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(218,41,UPPER('A'),'INDUSTRIAS MANUFACTURERAS',4120,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(219,41,UPPER('A'),'SUMINISTRO DE ELECTRICIDAD, GAS Y AGUA',4125,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(220,41,UPPER('A'),'CONSTRUCCION',4130,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(221,41,UPPER('A'),'COMERCIO AL POR MAYOR Y AL POR MENOR',4135,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(222,41,UPPER('A'),'HOTELES Y RESTAURANTES',4140,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(223,41,UPPER('A'),'TRANSPORTE, ALMACENAMIENTO Y COMUNICACIONES',4145,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(224,41,UPPER('A'),'ACTIVIDAD FINANCIERA',4150,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(225,41,UPPER('A'),'ACTIVIDADES INMOBILIARIAS, EMPRESARIALES Y DE ALQUILER',4155,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(226,41,UPPER('A'),'ENSEÑANZA',4160,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(227,41,UPPER('A'),'SERVICIOS SOCIALES Y DE SALUD',4165,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(228,41,UPPER('A'),'OTRAS ACTIVIDADES DE SERVICIOS COMUNITARIOS, SOCIALES Y PERSONALES',4170,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(229,41,UPPER('A'),'DEVOLUCIONES, REBAJAS Y DESCUENTOS EN VENTAS (DB)',4175,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(230,42,UPPER('A'),'OTRAS VENTAS',4205,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(231,42,UPPER('A'),'FINANCIEROS',4210,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(232,42,UPPER('A'),'DIVIDENDOS Y PARTICIPACIONES',4215,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(233,42,UPPER('A'),'ARRENDAMIENTOS',4220,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(234,42,UPPER('A'),'COMISIONES',4225,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(235,42,UPPER('A'),'HONORARIOS',4230,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(236,42,UPPER('A'),'SERVICIOS',4235,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(237,42,UPPER('A'),'UTILIDAD EN VENTA DE INVERSIONES',4240,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(238,42,UPPER('A'),'UTILIDAD EN VENTA DE PROPIEDADES PLANTA Y EQUIPO',4245,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(239,42,UPPER('A'),'UTILIDAD EN VENTA DE OTROS BIENES',4248,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(240,42,UPPER('A'),'RECUPERACIONES',4250,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(241,42,UPPER('A'),'INDEMNIZACIONES',4255,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(242,42,UPPER('A'),'PARTICIPACIONES EN CONCESIONES',4260,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(243,42,UPPER('A'),'INGRESOS DE EJERCICIOS ANTERIORES',4265,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(244,42,UPPER('A'),'DEVOLUCIONES, REBAJAS Y DESCUENTOS EN OTRAS VENTAS (DB)',4275,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(245,42,UPPER('A'),'DIVERSOS',4295,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(246,47,UPPER('A'),'CORRECCION MONETARIA',4705,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(247,51,UPPER('A'),'GASTOS DE PERSONAL',5105,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(248,51,UPPER('A'),'HONORARIOS',5110,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(249,51,UPPER('A'),'IMPUESTOS',5115,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(250,51,UPPER('A'),'ARRENDAMIENTOS',5120,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(251,51,UPPER('A'),'CONTRIBUCIONES Y AFILIACIONES',5125,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(252,51,UPPER('A'),'SEGUROS',5130,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(253,51,UPPER('A'),'SERVICIOS',5135,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(254,51,UPPER('A'),'GASTOS LEGALES',5140,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(255,51,UPPER('A'),'MANTENIMIENTO Y REPARACIONES',5145,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(256,51,UPPER('A'),'ADECUACION E INSTALACION',5150,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(257,51,UPPER('A'),'GASTOS DE VIAJE',5155,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(258,51,UPPER('A'),'DEPRECIACIONES',5160,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(259,51,UPPER('A'),'AMORTIZACIONES',5165,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(260,51,UPPER('A'),'DIVERSOS',5195,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(261,51,UPPER('A'),'PROVISIONES',5199,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(262,52,UPPER('A'),'GASTOS DE PERSONAL',5205,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(263,52,UPPER('A'),'HONORARIOS',5210,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(264,52,UPPER('A'),'IMPUESTOS',5215,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(265,52,UPPER('A'),'ARRENDAMIENTOS',5220,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(266,52,UPPER('A'),'CONTRIBUCIONES Y AFILIACIONES',5225,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(267,52,UPPER('A'),'SEGUROS',5230,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(268,52,UPPER('A'),'SERVICIOS',5235,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(269,52,UPPER('A'),'GASTOS LEGALES',5240,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(270,52,UPPER('A'),'MANTENIMIENTO Y REPARACIONES',5245,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(271,52,UPPER('A'),'ADECUACION E INSTALACION',5250,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(272,52,UPPER('A'),'GASTOS DE VIAJE',5255,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(273,52,UPPER('A'),'DEPRECIACIONES',5260,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(274,52,UPPER('A'),'AMORTIZACIONES',5265,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(275,52,UPPER('A'),'FINANCIEROS - REAJUSTE DEL SISTEMA',5270,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(276,52,UPPER('A'),'DIVERSOS',5295,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(277,52,UPPER('A'),'PROVISIONES',5299,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(278,53,UPPER('A'),'FINANCIEROS',5305,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(279,53,UPPER('A'),'PERDIDA EN VENTA Y RETIRO DE BIENES',5310,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(280,53,UPPER('A'),'GASTOS EXTRAORDINARIOS',5315,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(281,53,UPPER('A'),'GASTOS DIVERSOS',5395,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(282,54,UPPER('A'),'IMPUESTO DE RENTA Y COMPLEMENTARIOS',5405,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(283,59,UPPER('A'),'GANANCIAS Y PERDIDAS',5905,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(284,61,UPPER('A'),'AGRICULTURA, GANADERIA, CAZA Y SILVICULTURA',6105,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(285,61,UPPER('A'),'PESCA',6110,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(286,61,UPPER('A'),'EXPLOTACION DE MINAS Y CANTERAS',6115,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(287,61,UPPER('A'),'INDUSTRIAS MANUFACTURERAS',6120,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(288,61,UPPER('A'),'SUMINISTRO DE ELECTRICIDAD, GAS Y AGUA',6125,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(289,61,UPPER('A'),'CONSTRUCCION',6130,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(290,61,UPPER('A'),'COMERCIO AL POR MAYOR Y AL POR MENOR',6135,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(291,61,UPPER('A'),'HOTELES Y RESTAURANTES',6140,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(292,61,UPPER('A'),'TRANSPORTE, ALMACENAMIENTO Y COMUNICACIONES',6145,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(293,61,UPPER('A'),'ACTIVIDAD FINANCIERA',6150,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(294,61,UPPER('A'),'ACTIVIDADES INMOBILIARIAS, EMPRESARIALES Y DE ALQUILER',6155,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(295,61,UPPER('A'),'ENSEÑANZA',6160,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(296,61,UPPER('A'),'SERVICIOS SOCIALES Y DE SALUD',6165,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(297,61,UPPER('A'),'OTRAS ACTIVIDADES DE SERVICIOS COMUNITARIOS, SOCIALES Y PERSONALES',6170,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(298,62,UPPER('A'),'DE MERCANCIAS',6205,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(299,62,UPPER('A'),'DE MATERIAS PRIMAS',6210,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(300,62,UPPER('A'),'DE MATERIALES INDIRECTOS',6215,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(301,62,UPPER('A'),'COMPRA DE ENERGIA',6220,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(302,62,UPPER('A'),'DEVOLUCIONES REBAJAS Y DESCUENTOS EN COMPRAS (CR)',6225,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(303,81,UPPER('A'),'BIENES Y VALORES ENTREGADOS EN CUSTODIA',8105,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(304,81,UPPER('A'),'BIENES Y VALORES ENTREGADOS EN GARANTIA',8110,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(305,81,UPPER('A'),'BIENES Y VALORES EN PODER DE TERCEROS',8115,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(306,81,UPPER('A'),'LITIGIOS Y/O DEMANDAS',8120,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(307,81,UPPER('A'),'PROMESAS DE COMPRAVENTA',8125,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(308,81,UPPER('A'),'DIVERSAS',8195,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(309,83,UPPER('A'),'BIENES RECIBIDOS EN ARRENDAMIENTO FINANCIERO',8305,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(310,83,UPPER('A'),'TITULOS DE INVERSION NO COLOCADOS',8310,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(311,83,UPPER('A'),'PROPIEDADES PLANTA Y EQUIPO TOTALMENTE DEPRECIADOS, AGOTADOS Y/O AMORTIZADOS',8315,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(312,83,UPPER('A'),'CREDITOS A FAVOR NO UTILIZADOS',8320,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(313,83,UPPER('A'),'ACTIVOS CASTIGADOS',8325,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(314,83,UPPER('A'),'TITULOS DE INVERSION AMORTIZADOS',8330,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(315,83,UPPER('A'),'CAPITALIZACION POR REVALORIZACION DE PATRIMONIO',8335,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(316,83,UPPER('A'),'OTRAS CUENTAS DEUDORAS DE CONTROL',8395,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(317,83,UPPER('A'),'AJUSTES POR INFLACION ACTIVOS',8399,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(318,91,UPPER('A'),'BIENES Y VALORES RECIBIDOS EN CUSTODIA',9105,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(319,91,UPPER('A'),'BIENES Y VALORES RECIBIDOS EN GARANTIA',9110,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(320,91,UPPER('A'),'BIENES Y VALORES RECIBIDOS DE TERCEROS',9115,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(321,91,UPPER('A'),'LITIGIOS Y/O DEMANDAS',9120,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(322,91,UPPER('A'),'PROMESAS DE COMPRAVENTA',9125,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(323,91,UPPER('A'),'CONTRATOS DE ADMINISTRACION DELEGADA',9130,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(324,91,UPPER('A'),'CUENTAS EN PARTICIPACION',9135,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(325,91,UPPER('A'),'OTRAS RESPONSABILIDADES CONTINGENTES',9195,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(326,93,UPPER('A'),'CONTRATOS DE ARRENDAMIENTO FINANCIERO',9305,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(327,93,UPPER('A'),'OTRAS CUENTAS DE ORDEN ACREEDORAS DE CONTROL',9395,'descripcion');
INSERT INTO co_tcuen(cuen_cuen,cuen_grup,cuen_estado,cuen_nombre,cuen_codigo,cuen_descripcion)VALUES(328,93,UPPER('A'),'AJUSTES POR INFLACION PATRIMONIO',9399,'descripcion');
