--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(1, 1,UPPER('A'), 'DISPONIBLE', 'COMPRENDE LAS CUENTAS QUE REGISTRAN LOS RECURSOS DE LIQUIDEZ INMEDIATA, TOTAL O PARCIAL CON QUE CUENTA EL ENTE ECONOMICO.', 11);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(2, 1,UPPER('A'), 'INVERSIONES', 'COMPRENDE LAS CUENTAS QUE REGISTRAN LAS INVERSIONES EN ACCIONES, CUOTAS O PARTES DE INTERES SOCIAL, TITULOS VALORES,', 12);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(3, 1,UPPER('A'), 'DEUDORES', 'COMPRENDE EL VALOR DE LAS DEUDAS A CARGO DE TERCEROS Y A FAVOR DEL ENTE ECONOMICO, INCLUIDAS LAS COMERCIALES Y NO COMERCIALES.', 13);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(4, 1,UPPER('A'), 'INVENTARIOS', 'COMPRENDE TODOS AQUELLOS ARTICULOS, MATERIALES, SUMINISTROS, PRODUCTOS Y RECURSOS RENOVABLES Y NO RENOVABLES, ', 14);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(5, 2,UPPER('A'), 'OBLIGACIONES FINCANCIERAS', 'COMPRENDE EL VALOR DE LAS OBLIGACIONES CONTRAIDAS POR EL ENTE ECONOMICO MEDIANTE LA OBTENCION DE RECURSOS PROVENIENTES DE ESTABLECIMIENTOS,', 21);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(6, 2,UPPER('A'), 'PROVEEDORES', 'COMPRENDE EL VALOR DE LAS OBLIGACIONES A CARGO DEL ENTE ECONOMICO, POR CONCEPTO DE LA ADQUISICION DE BIENES Y/O SERVICIOS PARA LA FABRICACION,', 22);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(7, 2,UPPER('A'), 'CUENTAS POR PAGAR', 'COMPRENDE LAS OBLIGACIONES CONTRAIDAS POR EL ENTE ECONOMICO A FAVOR DE TERCEROS POR CONCEPTOS DIFERENTES A LOS PROVEEDORES Y OBLIGACIONES FINANCIERAS.', 23);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(8, 2,UPPER('A'), 'IMPUESTOS GRAVAMENES Y TASAS', 'COMPRENDE EL VALOR DE LOS GRAVAMENES DE CARACTER GENERAL Y OBLIGATORIOS A FAVOR DEL ESTADO Y A CARGO DEL ENTE ECONOMICO POR CONCEPTO DE LOS CALCULOS,', 24);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(9, 3,UPPER('A'), 'CAPITAL SOCIAL', 'COMPRENDE EL VALOR TOTAL DE LOS APORTES INICIALES Y LOS POSTERIORES AUMENTOS O DISMINUCIONES QUE LOS SOCIOS,', 31);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(10, 3,UPPER('A'), 'SUPERAVIT DE CAPITAL', 'COMPRENDE EL VALOR DE LAS CUENTAS QUE REFLEJAN EL INCREMENTO PATRIMONIAL OCASIONADO POR PRIMA EN COLOCACION DE ACCIONES,', 32);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(11, 3,UPPER('A'), 'RESERVAS', 'COMPRENDEN LOS VALORES QUE POR MANDATO EXPRESO DEL MAXIMO ORGANO SOCIAL, SE HAN APROPIADO DE LAS UTILIDADES LIQUIDAS DE EJERCICIOS ANTERIORES.', 33);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(12, 3,UPPER('A'), 'REVALORACION DEL PATRIMONIO', 'COMPRENDE EL VALOR DEL INCREMENTO PATRIMONIAL POR CONCEPTO Y DE LOS SALDOS ORIGINADOS EN SANEAMIENTOS FISCALES,', 34);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(13, 4,UPPER('A'), 'OPERACIONALES', 'COMPRENDE LOS VALORES RECIBIDOS Y/O CAUSADOS COMO RESULTADO DE LAS ACTIVIDADES DESARROLLADAS EN CUMPLIMIENTO DE SU OBJETO SOCIAL,', 41);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(14, 4,UPPER('A'), 'NO OPERACIONALES', 'COMPRENDE LOS INGRESOS PROVENIENTES DE TRANSACCIONES DIFERENTES A LOS DEL OBJETO SOCIAL O GIRO NORMAL DE LOS NEGOCIOS DEL ENTE ECONOMICO,', 42);
--INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(15, 4,UPPER('A'), 'AJUSTES POR INFLACION', 'REGISTRA LA CONTRAPARTIDA DE LA APLICACION DEL SISTEMA DE AJUSTES POR INFLACION PARA LOS DIFERENTES RUBROS QUE CONFORMAN LOS ESTADOS FINANCIEROS,', 47);

--INSERT JOHN 

INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(1,1,UPPER('A'),'DISPONIBLE','descripcion',11);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(2,1,UPPER('A'),'INVERSIONES','descripcion',12);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(3,1,UPPER('A'),'DEUDORES','descripcion',13);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(4,1,UPPER('A'),'INVENTARIOS','descripcion',14);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(5,1,UPPER('A'),'PROPIEDADES PLANTA Y EQUIPO','descripcion',15);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(6,1,UPPER('A'),'INTANGIBLES','descripcion',16);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(7,1,UPPER('A'),'DIFERIDOS','descripcion',17);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(8,1,UPPER('A'),'OTROS ACTIVOS','descripcion',18);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_NOMBRE, GRUP_DESCRIPCION, GRUP_CODIGO)VALUES(9,1,UPPER('A'),'VALORIZACIONES','descripcion',19);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(10,2,UPPER('A'),'descripcion','OBLIGACIONES FINANCIERAS',21);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(11,2,UPPER('A'),'descripcion','PROVEEDORES',22);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(12,2,UPPER('A'),'descripcion','CUENTAS POR PAGAR',23);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(13,2,UPPER('A'),'descripcion','IMPUESTOS, GRAVAMENES Y TASAS',24);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(14,2,UPPER('A'),'descripcion','OBLIGACIONES LABORALES',25);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(15,2,UPPER('A'),'descripcion','PASIVOS ESTIMADOS Y PROVISIONES',26);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(16,2,UPPER('A'),'descripcion','DIFERIDOS',27);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(17,2,UPPER('A'),'descripcion','OTROS PASIVOS',28);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(18,2,UPPER('A'),'descripcion','BONOS Y PAPELES COMERCIALES',29);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(19,3,UPPER('A'),'descripcion','CAPITAL SOCIAL',31);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(20,3,UPPER('A'),'descripcion','SUPERAVIT DE CAPITAL',32);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(21,3,UPPER('A'),'descripcion','RESERVAS',33);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(22,3,UPPER('A'),'descripcion','REVALORIZACION DEL PATRIMONIO',34);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(23,3,UPPER('A'),'descripcion','DIVIDENDOS O PARTICIPACIONES DECRETADOS EN ACCIONES, CUOTAS O PARTES DE INTERES SOCIAL',35);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(24,3,UPPER('A'),'descripcion','RESULTADOS DEL EJERCICIO',36);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(25,3,UPPER('A'),'descripcion','RESULTADOS DE EJERCICIOS ANTERIORES',37);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(26,3,UPPER('A'),'descripcion','SUPERAVIT POR VALORIZACIONES',38);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(27,4,UPPER('A'),'descripcion','OPERACIONALES',41);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(28,4,UPPER('A'),'descripcion','NO OPERACIONALES',42);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(29,4,UPPER('A'),'descripcion','AJUSTES POR INFLACION',47);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(30,5,UPPER('A'),'descripcion','OPERACIONALES DE ADMINISTRACION',51);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(31,5,UPPER('A'),'descripcion','OPERACIONALES DE VENTAS',52);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(32,5,UPPER('A'),'descripcion','NO OPERACIONALES',53);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(33,5,UPPER('A'),'descripcion','IMPUESTO DE RENTA Y COMPLEMENTARIOS',54);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(34,5,UPPER('A'),'descripcion','GANANCIAS Y PERDIDAS',59);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(35,6,UPPER('A'),'descripcion','COSTO DE VENTAS Y DE PRESTACION DE SERVICIOS',61);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(36,6,UPPER('A'),'descripcion','COMPRAS',62);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(37,7,UPPER('A'),'descripcion','MATERIA PRIMA',71);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(38,7,UPPER('A'),'descripcion','MANO DE OBRA DIRECTA',72);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(39,7,UPPER('A'),'descripcion','COSTOS INDIRECTOS',73);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(40,7,UPPER('A'),'descripcion','CONTRATOS DE SERVICIOS',74);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(41,8,UPPER('A'),'descripcion','DERECHOS CONTINGENTES',81);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(42,8,UPPER('A'),'descripcion','DEUDORAS FISCALES',82);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(43,8,UPPER('A'),'descripcion','DEUDORAS DE CONTROL',83);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(44,8,UPPER('A'),'descripcion','DERECHOS CONTINGENTES POR CONTRA (CR)',84);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(45,8,UPPER('A'),'descripcion','DEUDORAS FISCALES POR CONTRA (CR)',85);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(46,8,UPPER('A'),'descripcion','DEUDORAS DE CONTROL POR CONTRA (CR)',86);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(47,9,UPPER('A'),'descripcion','RESPONSABILIDADES CONTINGENTES',91);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(48,9,UPPER('A'),'descripcion','ACREEDORAS FISCALES',92);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(49,9,UPPER('A'),'descripcion','ACREEDORAS DE CONTROL',93);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(50,9,UPPER('A'),'descripcion','RESPONSABILIDADES CONTINGENTES POR CONTRA (DB)',94);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(51,9,UPPER('A'),'descripcion','ACREEDORAS FISCALES POR CONTRA (DB)',95);
INSERT INTO CO_TGRUP(GRUP_GRUP, GRUP_CLAS, GRUP_ESTADO, GRUP_DESCRIPCION,  GRUP_NOMBRE,GRUP_CODIGO)VALUES(52,9,UPPER('A'),'descripcion','ACREEDORAS DE CONTROL POR CONTRA (DB)',96);





