COMMENT ON TABLE  in_trmce                      IS          'Tabla en la cual se almacenara las remisiones de celulares';
COMMENT ON COLUMN in_trmce.rmce_rmce            IS          'Identificador primario de la tabla';
COMMENT ON COLUMN in_trmce.rmce_refe            IS          'Identificador de la tabla de referencia de celulares';
COMMENT ON COLUMN in_trmce.rmce_imei            IS          'Identificador unico de celular. ';
COMMENT ON COLUMN in_trmce.rmce_iccid           IS          'Identificador unico del plan';
COMMENT ON COLUMN in_trmce.rmce_valor           IS          'Valor por el cual fue vendido el celular';
COMMENT ON COLUMN in_trmce.rmce_comision        IS          'Comision obtenida por la venta del producto ';
COMMENT ON COLUMN in_trmce.rmce_tppl            IS          'Tipo de plan del celular ingresado';
COMMENT ON COLUMN in_trmce.rmce_fcve            IS          'Fecha de vencimiento del equipo';
COMMENT ON COLUMN in_trmce.rmce_fcsl            IS          'Fecha de salida del producto';
COMMENT ON COLUMN in_trmce.rmce_fcen            IS          'Fecha en la cual entro el producto';
COMMENT ON COLUMN in_trmce.rmce_tius_ent        IS          'Usuario el cual ingreso el celular';
COMMENT ON COLUMN in_trmce.rmce_tius_sal        IS          'Usuario el cual vendio el celular';
COMMENT ON COLUMN in_trmce.rmce_codigo          IS          'Codigo con el cual se identificara en el codigo de barras';
COMMENT ON COLUMN in_trmce.rmce_sede            IS          'Sede en el cual se encuentra el equipo celular';
COMMENT ON COLUMN in_trmce.rmce_estado          IS          'Indica el estado en cual se encuentra en el momento el equipo celular E(En estand listo para vender) V(Vendido) D(Devuelto)';
COMMENT ON COLUMN in_trmce.rmce_pagado          IS          'Indica si el equipo ya fue pagado a el proveedor si ya fue cancelado';
COMMENT ON COLUMN in_trmce.rmce_comdev          IS          'Aplica si es equipo fue devuelto a el proveedor por alguna razon (Comentario de devolucion)';
COMMENT ON COLUMN in_trmce.rmce_trans          IS           'Identificador con el cual cual fue la transaccion realizada por si en una sola transaccion se realizan dos compras de equipos';
COMMENT ON COLUMN in_trmce.rmce_clien          IS           'Indica el cliente el cual compro el equipo celular';
