CREATE TABLE AD_TPARSADM(
PARSADM_PARSADM          SERIAL        ,
PARSADM_NOMBRE           VARCHAR(2000) ,
PARSADM_ESTADO           VARCHAR(2)    ,
PARSADM_VALOR            VARCHAR(2000) ,
PRIMARY KEY (PARSADM_PARSADM)
);
