ALTER TABLE IN_TDSHA 
ADD CONSTRAINT DSHA_BANO_CHK CHECK (DSHA_BANO in ('S','N'))
;

ALTER TABLE IN_TDSHA 
ADD CONSTRAINT DSHA_TELEVISON_CHK CHECK (DSHA_TELEVISON in ('S','N'))
;

ALTER TABLE IN_TDSHA 
ADD CONSTRAINT DSHA_CABLE_CHK CHECK (DSHA_CABLE in ('S','N'))
;

ALTER TABLE IN_TDSHA 
ADD CONSTRAINT DSHA_CAMA_AUX_CHK CHECK (DSHA_CAMA_AUX in ('S','N'))
;

ALTER TABLE IN_TDSHA 
ADD CONSTRAINT DSHA_ESTADO_CHK CHECK (DSHA_CAMA_AUX in ('S','N'))
;
ALTER TABLE IN_TDSHA 
ADD CONSTRAINT DSHA_DISP_ACTU_CHK CHECK (DSHA_DISP_ACTU in ('D','O'))
;