ALTER TABLE US_TTIUS ADD CONSTRAINT TIUS_CAMBIO_CONTRA_CHK CHECK (TIUS_CAMBIO_CONTRA in ('S','N'));

ALTER TABLE US_TTIUS ADD CONSTRAINT TIUS_ESTADO_CHK CHECK (TIUS_ESTADO in ('A','I','X'));

ALTER TABLE US_TTIUS ADD CONSTRAINT TIUS_TIPO_USUARIO_CHK CHECK (TIUS_TIPO_USUARIO in ('AD','AM','CA'));
