COMMENT ON TABLE  IN_TDSHA                            IS          'Tabla encargada de tener la descripcion de las habitaciones';
COMMENT ON COLUMN IN_TDSHA.DSHA_DSHA                  IS          'Identificador primario de la tabla';
COMMENT ON COLUMN IN_TDSHA.DSHA_NUM_HAB               IS          'Numero de la habitacion PISO E IDENTIFICADOR';
COMMENT ON COLUMN IN_TDSHA.DSHA_FEC_INGRESO           IS          'Fecha en la cual se modifico el registro';
COMMENT ON COLUMN IN_TDSHA.DSHA_NUM_MAX_PERS          IS          'Numero maximo de personas que puede alojar la habitacion';
COMMENT ON COLUMN IN_TDSHA.DSHA_NUM_MIN_PERS          IS          'Numero minimo de personas que puede alojar la habitacion';
COMMENT ON COLUMN IN_TDSHA.DSHA_BANO                  IS          'Indica si la habitacion tiene baño privado';
COMMENT ON COLUMN IN_TDSHA.DSHA_TELEVISON             IS          'Indica si la habitacion tiene television';
COMMENT ON COLUMN IN_TDSHA.DSHA_CABLE                 IS          'Indica si la habitacion tiene television por cable';
COMMENT ON COLUMN IN_TDSHA.DSHA_NUM_CAMAS             IS          'Indica el numero de camas de la habitacion';
COMMENT ON COLUMN IN_TDSHA.DSHA_CAMA_AUX              IS          'Inidica si la habitacion tiene cama auxiliar';
COMMENT ON COLUMN IN_TDSHA.DSHA_ESTADO                IS          'Inidica estado de la habitacion si se encuentra activa(A) o inactiva(I)';
COMMENT ON COLUMN IN_TDSHA.DSHA_DISP_ACTU             IS          'Indica la disponibilidad acutual de la habitación Disponible(D) Ocupada(O)';
COMMENT ON COLUMN IN_TDSHA.DSHA_IVA                   IS          'Indica el valor de iva que se le cobrara a la habitacion';
