USE HOTEL;
-- CREAMOS LA TABLA HABITACIONES
-- Tabla en la cual se almacenara la inforamcion general de las habitaciones
-- que ofrece el hotel
-- LAS SIGLAS SE = SERVICIO  Y IGHA = INFORMACION GENERAL DE LAS HABITACIONES
DROP TABLE IF EXISTS SE_TIGHA;

CREATE TABLE SE_TIGHA(
	IGHA_IGHA        	  INT        			 NOT NULL 		AUTO_INCREMENT ,	-- IDENTIFICADOR DE LA TABLA
	IGHA_NUM_HABI 		  INT					     NOT NULL										 ,	-- NUMERO DE LA HABITACION DADO POR EL HOTEL
	IGHA_NUM_CAMA_S  	  INT  			       NOT NULL										 ,  -- NUMERO DE CAMAS SENCILLAS QUE TIENE LA HABITACION
	IGHA_NUM_CAMA_D     INT              NOT NULL                    ,  -- NUMERO DE CAMAS DOBLES QUE TIENE LA HABITACION
	IGHA_TELE         	VARCHAR(1)       NOT NULL                 	 ,  -- INDICA SI LA HABITACION TIENE TELEVISION SI(S) NO(N)
	IGHA_BANO  	        VARCHAR(1)       NOT NULL										 ,  -- INDICA SI LA HABITACION TIENE BAÑO SI(S) NO(N)
	IGHA_NUM_PER        INT              NOT NULL                    ,  -- NUMERO IDEAL DE PERSONAS PARA LA HABITACION
	IGHA_MAX_PERS			  INT              NOT NULL							 			 ,  -- INDICA EL NUMERO MAXIMO DE PERSONAS PERMITIDO EN LA HABITACION
	IGHA_CAMA_AUX      	VARCHAR(1)       NOT NULL									   ,  -- INDICA SI TIENE CAMA AUXILIAR SI(S) NO(N)
	PRIMARY KEY (IGHA_IGHA)
); 

